### ISSUE TITLE
Error mapping issue

### ISSUE THREAD

**Issue by qodesmith** [qodesmith/artist-hub#2]
@h4w5 @bigtone1284 (not sure of Will's github name).

Gentlemen,

In various routes, most of us are using code like such:
`var errors = err.errors.map(function(error) {
				return error.path + ' - ' + error.message;
			});
			res
				.status(422)
				.send(errors);
		});`

First, I'm getting a map error in the terminal. Second, I need a bit of a refresher on exactly what this code is doing. When McK gave it to us, he did it at the speed of light!  Here is the full route so you see whats going on:
```
songRouter.post('/', authenticate, function(req, res) {
	req.body.user_id = req.session.currentUser;

	Song
		.create(req.body)
		.then(function(song) {
			res.send(song);
		}, function(err) {
			var errors = err.errors.map(function(error) {
				return error.path + ' - ' + error.message;
			});
			res
				.status(422)
				.send(errors);
		});
});
```

**Comment by h4w5** [comment]
Now *this* is a good issue! You can even give it labels like "question" and "bug"!

Can you paste the error output in here?

**Comment by qodesmith** [comment]
I'll paste it, just have to make the ajax call again. Give me one sec. The error may be looooong tho....

**Comment by qodesmith** [comment]
```
Executing (default): INSERT INTO "songs" ("id","url","title","description","genre","user_id","updatedAt","createdAt") VALUES (DEFAULT,'http://example.com','First Test Song','Testing out the creation of a song.','Hip-Hop',1,'2015-04-20 18:48:50.816 +00:00','2015-04-20 18:48:50.816 +00:00') RETURNING *;
Possibly unhandled TypeError: Cannot read property 'map' of undefined
    at null.<anonymous> (/Users/QuestTheWordsmith/artist-hub/routers/song_router.js:63:27)
    at tryCatch1 (/Users/QuestTheWordsmith/artist-hub/node_modules/sequelize/node_modules/bluebird/js/main/util.js:45:21)
    at Promise._callHandler (/Users/QuestTheWordsmith/artist-hub/node_modules/sequelize/node_modules/bluebird/js/main/promise.js:571:13)
    at Promise._settlePromiseFromHandler (/Users/QuestTheWordsmith/artist-hub/node_modules/sequelize/node_modules/bluebird/js/main/promise.js:581:18)
    at Promise._settlePromiseAt (/Users/QuestTheWordsmith/artist-hub/node_modules/sequelize/node_modules/bluebird/js/main/promise.js:713:18)
    at Promise._settlePromiseAt (/Users/QuestTheWordsmith/artist-hub/node_modules/sequelize/lib/promise.js:76:18)
    at Promise._settlePromises (/Users/QuestTheWordsmith/artist-hub/node_modules/sequelize/node_modules/bluebird/js/main/promise.js:854:14)
    at Async._consumeFunctionBuffer (/Users/QuestTheWordsmith/artist-hub/node_modules/sequelize/node_modules/bluebird/js/main/async.js:85:12)
    at Async.consumeFunctionBuffer (/Users/QuestTheWordsmith/artist-hub/node_modules/sequelize/node_modules/bluebird/js/main/async.js:40:14)
    at process._tickCallback (node.js:355:11)
```

Line 63 in sound_router.js reads as follows:
`var errors = err.errors.map(function(error) {`

**Comment by h4w5** [comment]
Awesome thanks! looks like there is no property `errors` of the object `err`. Drop a breakpoint in the code right above that line and inspect the `err` object. Or `console.log(err)` right above it. Send the result of that log.

**Comment by qodesmith** [comment]
```
{ [SequelizeDatabaseError: null value in column "album_id" violates not-null constraint]
  name: 'SequelizeDatabaseError',
  message: 'null value in column "album_id" violates not-null constraint',
  parent: 
   { [error: null value in column "album_id" violates not-null constraint]
     name: 'error',
     length: 327,
     severity: 'ERROR',
     code: '23502',
     detail: 'Failing row contains (13, http://example.com, First Test Song, Testing out the creation of a song., Hip-Hop, null, null, 1, null, 2015-04-20 18:59:56.35+00, 2015-04-20 18:59:56.35+00).',
     hint: undefined,
     position: undefined,
     internalPosition: undefined,
     internalQuery: undefined,
     where: undefined,
     schema: 'public',
     table: 'songs',
     column: 'album_id',
     dataType: undefined,
     constraint: undefined,
     file: 'execMain.c',
     line: '1632',
     routine: 'ExecConstraints',
     sql: 'INSERT INTO "songs" ("id","url","title","description","genre","user_id","updatedAt","createdAt") VALUES (DEFAULT,\'http://example.com\',\'First Test Song\',\'Testing out the creation of a song.\',\'Hip-Hop\',1,\'2015-04-20 18:59:56.350 +00:00\',\'2015-04-20 18:59:56.350 +00:00\') RETURNING *;' },
  original: 
   { [error: null value in column "album_id" violates not-null constraint]
     name: 'error',
     length: 327,
     severity: 'ERROR',
     code: '23502',
     detail: 'Failing row contains (13, http://example.com, First Test Song, Testing out the creation of a song., Hip-Hop, null, null, 1, null, 2015-04-20 18:59:56.35+00, 2015-04-20 18:59:56.35+00).',
     hint: undefined,
     position: undefined,
     internalPosition: undefined,
     internalQuery: undefined,
     where: undefined,
     schema: 'public',
     table: 'songs',
     column: 'album_id',
     dataType: undefined,
     constraint: undefined,
     file: 'execMain.c',
     line: '1632',
     routine: 'ExecConstraints',
     sql: 'INSERT INTO "songs" ("id","url","title","description","genre","user_id","updatedAt","createdAt") VALUES (DEFAULT,\'http://example.com\',\'First Test Song\',\'Testing out the creation of a song.\',\'Hip-Hop\',1,\'2015-04-20 18:59:56.350 +00:00\',\'2015-04-20 18:59:56.350 +00:00\') RETURNING *;' },
  sql: 'INSERT INTO "songs" ("id","url","title","description","genre","user_id","updatedAt","createdAt") VALUES (DEFAULT,\'http://example.com\',\'First Test Song\',\'Testing out the creation of a song.\',\'Hip-Hop\',1,\'2015-04-20 18:59:56.350 +00:00\',\'2015-04-20 18:59:56.350 +00:00\') RETURNING *;' }
```

**Comment by qodesmith** [comment]
I can see now that album_id is null when it shouldn't be. That's another issue because I want the column to accept null. None the less, not sure why .map is failing.

**Comment by qodesmith** [comment]
If you're in the building, I can come to you. Would that be better? I'm currently on the 4th floor.

**Comment by qodesmith** [comment]
I think I might get it now... since the error is a database error, there is no validation error from the model or client side error to display, hence on those sides, "everything went well".

**Comment by h4w5** [comment]
@DrRobotmck @harimohanraj89 you guys should be proud of this one! :) I think Aaron id'ed an issue with the example code worth reviewing, that it's assuming an error format that doesn't work when the error is bubbling up from the database layer.
